In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

## Q1

In [2]:
np.__version__

'1.20.1'

In [4]:
!pip install wget

In [5]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

100% [......................................................] 1475504 / 1475504
Saved under data (1).csv


In [3]:
df = pd.read_csv('data.csv')

## Q2

In [4]:
df.shape[0]

11914

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

## Q3

In [6]:
df['Make'].value_counts(sort=True).head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Q4

In [7]:
df[df['Make'] == 'Audi']['Model'].nunique()

34

## Q5

In [8]:
(df.isna().sum().sort_values(ascending=False) > 0).sum()

5

## Q6

In [9]:
df['Engine Cylinders'].median()

6.0

In [10]:
df['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [11]:
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode())

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [12]:
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [13]:
df['Engine Cylinders'].median()

6.0

## Q7

In [14]:
lotus_df = df[df['Make'] == 'Lotus'][["Engine HP", "Engine Cylinders"]]

In [15]:
lotus_df.drop_duplicates(inplace=True)

In [16]:
X = lotus_df.to_numpy()

In [17]:
X 

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [18]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [19]:
IXTX = np.linalg.inv(XTX)

In [20]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [21]:
w = (IXTX.dot(X.T)).dot(y)
w

array([  4.59494481, -63.56432501])